service: spark-sandbox

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 256
  timeout: 20

package:
  artifact: build/libs/${self:service}-all.jar

functions:
  hello:
    handler: com.merricklabs.sparksandbox.StreamLambdaHandler
    events:
      - http:
          path: /{proxy+}
          method: any