service: spark-sandbox

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 512
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "*"
  environment:
    DYNAMODB_ENDPOINT: ${self:custom.dynamoEndpoint}
    DYNAMODB_REGION: ${self:provider.region}
    CALENDAR_TABLE_NAME: ${self:custom.calendarTableName}
    FILTER_TABLE_NAME: ${self:custom.filterTableName}
    GEOCODER_API_KEY: ${env:GEOCODER_API_KEY}

package:
  artifact: build/libs/${self:service}.jar

functions:
  filter:
    handler: com.merricklabs.aion.handlers.FilterHandler
    events:
      - http:
          path: /filters
          method: post
      - http:
          path: /filters/{filterId}
          method: get
          request:
            parameters:
              paths:
                filterId: true

